//! Encode numeric trees exported from the original server by Probe.java.
//! The output uses cubiomes' MIT `tables/btree21wd.h` representation.
//! Copyright (c) 2020 Cubitect; the upstream license is retained in the fork.
use crate::release::Result;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

struct Node {
    bounds: [[i32; 2]; 6],
    biome: Option<u8>,
    children: Vec<usize>,
    depth: usize,
    size: usize,
}

fn flatten(value: &Value, depth: usize, ids: &Value, nodes: &mut Vec<Node>) -> Result<usize> {
    let intervals = value["bounds"].as_array().ok_or("missing tree bounds")?;
    if intervals.len() != 7 || intervals[6] != serde_json::json!([0, 0]) {
        return Err("Overworld tree has unsupported nonzero offset".into());
    }
    let mut bounds = [[0; 2]; 6];
    for (i, bound) in bounds.iter_mut().enumerate() {
        for (j, coordinate) in bound.iter_mut().enumerate() {
            *coordinate = intervals[i][j]
                .as_i64()
                .and_then(|n| i32::try_from(n).ok())
                .ok_or("invalid parameter bound")?;
        }
    }
    let biome = value["biome"]
        .as_str()
        .map(|name| {
            ids[name.strip_prefix("minecraft:").unwrap_or(name)]
                .as_u64()
                .and_then(|id| u8::try_from(id).ok())
                .ok_or_else(|| format!("unknown biome {name}"))
        })
        .transpose()?;
    let index = nodes.len();
    nodes.push(Node {
        bounds,
        biome,
        children: vec![],
        depth,
        size: 0,
    });
    if let Some(children) = value["children"].as_array() {
        for child in children {
            let child = flatten(child, depth + 1, ids, nodes)?;
            nodes[index].children.push(child);
        }
    }
    if biome.is_some() == !nodes[index].children.is_empty() {
        return Err("tree node must be a leaf or a nonempty branch".into());
    }
    nodes[index].size = nodes.len() - index;
    Ok(index)
}

pub(super) fn encode(tree: &Value, ids: &Value, name: &str) -> Result<String> {
    if name.is_empty() || !name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_') {
        return Err("invalid table identifier".into());
    }
    let mut nodes = vec![];
    flatten(tree, 0, ids, &mut nodes)?;
    if nodes.len() >= 0xff00 {
        return Err("tree exceeds cubiomes' index capacity".into());
    }
    let order = nodes.iter().map(|n| n.children.len()).max().unwrap_or(0);
    let depth = nodes.iter().map(|n| n.depth).max().unwrap_or(0);
    let mut steps = vec![];
    for d in 1..=depth {
        steps.push(
            nodes
                .iter()
                .filter(|n| n.depth == d)
                .map(|n| n.size)
                .max()
                .unwrap(),
        );
    }
    steps.push(0);
    // Upstream's synthetic root is a zero point, never a candidate biome.
    // Reproduces every numeric word of the 1.21.4 baseline.
    nodes[0].bounds = [[0; 2]; 6];
    let bounds: BTreeSet<_> = nodes.iter().flat_map(|n| n.bounds).collect();
    if bounds.len() > 256 {
        return Err("too many parameter intervals".into());
    }
    let indices: BTreeMap<_, _> = bounds.iter().enumerate().map(|(i, p)| (*p, i)).collect();
    let mut output = String::from(
        "/* Generated by cargo xtask cubiomes-btree; see the data provenance files. */\n#include <inttypes.h>\n\n",
    );
    writeln!(output, "enum {{ {name}_order = {order} }};\n").unwrap();
    writeln!(
        output,
        "static const uint32_t {name}_steps[] = {{ {} }};\n",
        steps
            .iter()
            .map(usize::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    writeln!(output, "static const int32_t {name}_param[][2] = {{").unwrap();
    for [min, max] in bounds {
        writeln!(output, "    {{{min}, {max}}},").unwrap();
    }
    writeln!(output, "}};\n\nstatic const uint64_t {name}_nodes[] = {{").unwrap();
    for node in &nodes {
        let top = match node.biome {
            Some(id) => 0xff00 | usize::from(id),
            None => node.children[0],
        };
        let mut word = (top as u64) << 48;
        for (i, bound) in node.bounds.iter().enumerate() {
            word |= (indices[bound] as u64) << (8 * i);
        }
        writeln!(output, "    UINT64_C(0x{word:016X}),").unwrap();
    }
    writeln!(output, "}};").unwrap();
    writeln!(output, "\nstatic const uint32_t {name}_ends[] = {{").unwrap();
    for (i, node) in nodes.iter().enumerate() {
        writeln!(output, "    {},", i + node.size).unwrap();
    }
    writeln!(output, "}};").unwrap();
    Ok(output)
}

pub(super) fn run(input: &Path, output: &Path, name: &str) -> Result {
    let probe = super::read_tree(input)?;
    let ids: Value =
        serde_json::from_str(include_str!("biome-ids.json")).map_err(|e| e.to_string())?;
    let encoded = encode(&probe["trees"]["overworld"], &ids, name)?;
    std::fs::write(output, encoded).map_err(|e| e.to_string())
}
