[package]
name = "lumilio-plugin-world-explorer"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
lumilio-plugin-api.workspace = true
lumilio-cubiomes.workspace = true
lumilio-anvil.workspace = true
lumilio-nbt.workspace = true
serde_json.workspace = true
xaero-core = { path = "../../vendor/xaerotools/crates/xaero-core" }

[lints]
workspace = true
