[package]
name = "lumilio-cubiomes"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[build-dependencies]
cc = "1"

[lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
