[package]
name = "lumilio-app"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gpui-kit.workspace = true
lumilio-core.workspace = true
lumilio-plugin-api.workspace = true
lumilio-plugin-crash-analyzer.workspace = true
lumilio-plugin-litematica.workspace = true
lumilio-plugin-modrinth.workspace = true
lumilio-plugin-discord.workspace = true
lumilio-ui.workspace = true
futures = "0.3"
reqwest.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
